apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-app
        image: daniilbutnev/todo-app:v1   
        ports:
          - containerPort: 3000        
        env:
          - name: PGHOST
            value: "db.default.svc.cluster.local"
          - name: PGUSER
            value: "postgres"
          - name: PGPASSWORD
            value: "secret"
          - name: PGDATABASE
            value: "todo_db"